import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "AssetInvader",
  description: "Generated by AssetInvader",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
      <h1><Link href="/">AssetInvader</Link></h1>
      <ol>
        <li><Link href="/menu/1">유형별 자산관리</Link></li>
        <li><Link href="/menu/2">분류별 자산관리</Link></li>
      </ol>
      {children}
      </body>
    </html>
  );
}
