import "./globals.css";

export const metadata = {
  title: "AssetInvader",
  description: "Generated by AssetInvader",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
      <h1><a href="/">AssetInvader</a></h1>
      <ol>
        <li><a href="/menu/1">유형별 자산관리</a></li>
        <li><a href="/menu/2">분류별 자산관리</a></li>
      </ol>
      {children}
      </body>
    </html>
  );
}
